<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Mono.Cli</RootNamespace>
    <AssemblyName>Mono.Cli</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Mono.Protocol\Mono.Protocol.csproj" />
    <ProjectReference Include="..\Mono.Shared\Mono.Shared.csproj" />
  </ItemGroup>
</Project>

