<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Auralis.Control</RootNamespace>
    <AssemblyName>Auralis.Control</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auralis.Protocol\Auralis.Protocol.csproj" />
    <ProjectReference Include="..\Auralis.Shared\Auralis.Shared.csproj" />
  </ItemGroup>
</Project>
