<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Auralis.Protocol</RootNamespace>
    <AssemblyName>Auralis.Protocol</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Auralis.Shared\Auralis.Shared.csproj" />
  </ItemGroup>
</Project>
